import { useMemo, useState } from 'react';
import { Download, Edit3, Eye, Filter, Plus, Search, SlidersHorizontal, Sparkles, UsersRound } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { demoCustomers, formatDate, formatVnd, initials } from '@/data/demo';
import type { Customer } from '@/types/domain';
import { Badge, EmptyState, Modal, PageHeader, Panel, PanelHeader, Toast } from '@/components/primitives';

function CustomerForm({ initial, onSave, onClose }: { initial?: Customer; onSave: (customer: Customer) => void; onClose: () => void }) {
  const [name, setName] = useState(initial?.fullName ?? '');
  const [phone, setPhone] = useState(initial?.phone ?? '');
  const [gender, setGender] = useState(initial?.gender ?? 'Nữ');
  const submit = (event: React.FormEvent) => { event.preventDefault(); onSave({ id: initial?.id ?? `cus-${Date.now()}`, fullName: name || 'Khách chưa đặt tên', phone, gender: gender as Customer['gender'], joinedAt: initial?.joinedAt ?? new Date().toISOString(), visitCount: initial?.visitCount ?? 0, totalSpend: initial?.totalSpend ?? 0, loyaltyPoints: initial?.loyaltyPoints ?? 0, tags: initial?.tags ?? ['Mới'] }); };
  return <Modal title={initial ? 'Chỉnh sửa khách hàng' : 'Thêm khách hàng'} description="Thông tin demo được lưu trong phiên làm việc này." onClose={onClose}><form onSubmit={submit} className="space-y-4 p-5"><div><label className="label" htmlFor="customer-name">Họ và tên</label><input id="customer-name" required className="input" value={name} onChange={(event) => setName(event.target.value)} data-testid="input-customer-name" placeholder="Ví dụ: Nguyễn Minh Anh" /></div><div><label className="label" htmlFor="customer-phone">Số điện thoại</label><input id="customer-phone" required className="input" value={phone} onChange={(event) => setPhone(event.target.value)} data-testid="input-customer-phone" placeholder="090 000 0000" /></div><div><label className="label" htmlFor="customer-gender">Giới tính</label><select id="customer-gender" className="input" value={gender} onChange={(event) => setGender(event.target.value as Customer['gender'])} data-testid="select-customer-gender"><option>Nữ</option><option>Nam</option><option>Khác</option></select></div><div className="flex justify-end gap-2 pt-2"><button type="button" className="btn btn-soft" onClick={onClose} data-testid="button-cancel-customer">Huỷ</button><button type="submit" className="btn btn-primary" data-testid="button-save-customer"><Plus size={15} /> Lưu khách hàng</button></div></form></Modal>;
}

export function CustomersPage() {
  const [customers, setCustomers] = useState(demoCustomers);
  const [query, setQuery] = useState('');
  const [editing, setEditing] = useState<Customer | undefined>();
  const [formOpen, setFormOpen] = useState(false);
  const [toast, setToast] = useState('');
  const filtered = useMemo(() => customers.filter((customer) => `${customer.fullName} ${customer.phone}`.toLowerCase().includes(query.toLowerCase())), [customers, query]);
  const saveCustomer = (customer: Customer) => { setCustomers((current) => current.some((item) => item.id === customer.id) ? current.map((item) => item.id === customer.id ? customer : item) : [customer, ...current]); setFormOpen(false); setEditing(undefined); setToast('Đã lưu khách hàng trong dữ liệu demo.'); };
  return <div className="page-wrap">
    <PageHeader kicker="Quan hệ khách hàng" title="Khách hàng" subtitle={`${customers.length} hồ sơ tại MEE Quận 1`} actions={<><button className="btn btn-soft hide-mobile" onClick={() => setToast('Bản xuất dữ liệu demo đã sẵn sàng.')} data-testid="button-export-customers"><Download size={15} /> Xuất danh sách</button><button className="btn btn-primary" onClick={() => { setEditing(undefined); setFormOpen(true); }} data-testid="button-add-customer"><Plus size={15} /> Thêm khách</button></>} />
    <Panel testId="panel-customers"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div className="relative min-w-[230px] flex-1"><Search size={16} className="absolute left-3 top-3 text-muted-foreground" /><input className="input pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm theo tên hoặc số điện thoại..." aria-label="Tìm khách hàng" data-testid="input-search-customers" /></div><div className="flex gap-2"><button className="btn btn-soft" onClick={() => setToast('Bộ lọc nâng cao sẽ kết nối với Supabase sau.')} data-testid="button-filter-customers"><Filter size={15} /> <span className="hide-mobile">Bộ lọc</span></button><button className="btn btn-soft" onClick={() => setToast('Đã mở tuỳ chỉnh cột demo.')} data-testid="button-customize-customers"><SlidersHorizontal size={15} /></button></div></div>
      {filtered.length === 0 ? <EmptyState icon={UsersRound} title="Chưa tìm thấy khách hàng" description="Thử một tên khác hoặc tạo hồ sơ mới cho vị khách đầu tiên." action={<button className="btn btn-primary" onClick={() => setFormOpen(true)} data-testid="button-empty-add-customer"><Plus size={15} /> Thêm khách hàng</button>} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Khách hàng</th><th>Liên hệ</th><th>Lần ghé gần nhất</th><th>Điểm</th><th>Chi tiêu</th><th className="text-right">Thao tác</th></tr></thead><tbody>{filtered.map((customer) => <tr key={customer.id} data-testid={`row-customer-${customer.id}`}><td><Link href={`/customers/${customer.id}`} className="flex items-center gap-3" data-testid={`link-customer-${customer.id}`}><div className="avatar">{initials(customer.fullName)}</div><div><div className="font-bold">{customer.fullName}</div><div className="mt-1 flex gap-1">{customer.tags.slice(0, 2).map((tag) => <Badge key={tag} tone={tag === 'VIP' ? 'coral' : 'default'}>{tag}</Badge>)}</div></div></Link></td><td><div className="font-mono-app text-xs">{customer.phone}</div><div className="mt-1 text-[10px] text-muted-foreground">{customer.email ?? 'Chưa cập nhật email'}</div></td><td>{customer.lastVisit ? formatDate(customer.lastVisit) : 'Chưa ghé'}</td><td><span className="font-mono-app text-xs text-primary">{customer.loyaltyPoints.toLocaleString('vi-VN')}</span></td><td className="font-mono-app text-xs">{formatVnd(customer.totalSpend)}</td><td><div className="flex justify-end gap-1"><Link href={`/customers/${customer.id}`} className="btn btn-ghost !p-2" aria-label={`Xem ${customer.fullName}`} data-testid={`button-view-customer-${customer.id}`}><Eye size={15} /></Link><button className="btn btn-ghost !p-2" onClick={() => { setEditing(customer); setFormOpen(true); }} aria-label={`Sửa ${customer.fullName}`} data-testid={`button-edit-customer-${customer.id}`}><Edit3 size={15} /></button></div></td></tr>)}</tbody></table></div>}
    </Panel>
    <div className="mt-3 flex items-center justify-between text-[11px] text-muted-foreground"><span>Hiển thị {filtered.length} trên {customers.length} khách hàng</span><span className="font-mono-app">DEMO DATA · LOCAL SESSION</span></div>
    {formOpen && <CustomerForm initial={editing} onSave={saveCustomer} onClose={() => { setFormOpen(false); setEditing(undefined); }} />}
    {toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>;
}

export function CustomerProfilePage() {
  const { id } = useParams<{ id: string }>();
  const customer = demoCustomers.find((item) => item.id === id) ?? demoCustomers[0];
  const [toast, setToast] = useState('');
  return <div className="page-wrap">
    <div className="mb-6 flex items-center gap-2 text-xs text-muted-foreground"><Link href="/customers" className="font-bold text-primary" data-testid="link-back-customers">Khách hàng</Link><span>/</span><span>Hồ sơ khách hàng</span></div>
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div className="flex items-center gap-4"><div className="avatar h-16 w-16 text-lg">{initials(customer.fullName)}</div><div><div className="page-kicker">Hồ sơ khách hàng</div><h1 className="page-title">{customer.fullName}</h1><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span>{customer.phone}</span><span>·</span><Badge tone="coral">{customer.tags[0]}</Badge></div></div></div><div className="flex gap-2"><button className="btn btn-soft" onClick={() => setToast('Chế độ chỉnh sửa hồ sơ đã sẵn sàng cho Supabase.')} data-testid="button-edit-profile"><Edit3 size={15} /> Chỉnh sửa</button><Link href="/booking" className="btn btn-primary" data-testid="link-book-profile"><Plus size={15} /> Tạo lịch hẹn</Link></div></div>
    <div className="section-grid three-col mb-5"><div className="panel metric-card"><div className="metric-label">Tổng chi tiêu</div><div className="metric-value text-xl">{formatVnd(customer.totalSpend)}</div><div className="metric-note">Hạng {customer.tags.includes('VIP') ? 'MEE Signature' : 'MEE Member'}</div></div><div className="panel metric-card"><div className="metric-label">Số lần ghé</div><div className="metric-value">{customer.visitCount}</div><div className="metric-note">Lần gần nhất {customer.lastVisit ? formatDate(customer.lastVisit) : '—'}</div></div><div className="panel metric-card"><div className="metric-label">Điểm loyalty</div><div className="metric-value">{customer.loyaltyPoints.toLocaleString('vi-VN')}</div><div className="metric-note">POINT balance</div></div></div>
    <div className="section-grid two-col"><Panel testId="panel-profile-history"><PanelHeader title="Lịch sử gần đây" caption="Các chạm dịch vụ đã ghi nhận" /><div className="timeline-item"><div className="timeline-dot" /><div><div className="text-xs font-bold">Chăm sóc da chuyên sâu</div><div className="mt-1 text-[11px] text-muted-foreground">28.06.2024 · Thảo Vy · {formatVnd(680000)}</div></div><Badge tone="green">Đã thanh toán</Badge></div><div className="timeline-item"><div className="timeline-dot" /><div><div className="text-xs font-bold">Tinh chất phục hồi MEE</div><div className="mt-1 text-[11px] text-muted-foreground">18.06.2024 · Lễ tân · {formatVnd(790000)}</div></div><Badge>Đã thanh toán</Badge></div><div className="timeline-item"><div className="timeline-dot" /><div><div className="text-xs font-bold">Massage trị liệu cổ vai gáy</div><div className="mt-1 text-[11px] text-muted-foreground">04.06.2024 · Thảo Vy · {formatVnd(520000)}</div></div><Badge tone="green">Đã thanh toán</Badge></div></Panel><div className="space-y-[18px]"><Panel testId="panel-profile-info"><PanelHeader title="Thông tin nhanh" /><div className="space-y-3 p-5 text-xs"><div className="flex justify-between gap-4"><span className="text-muted-foreground">Ngày tham gia</span><strong>{formatDate(customer.joinedAt)}</strong></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Sinh nhật</span><strong>{customer.birthday ? formatDate(customer.birthday) : 'Chưa cập nhật'}</strong></div><div className="flex justify-between gap-4"><span className="text-muted-foreground">Giới tính</span><strong>{customer.gender}</strong></div></div></Panel><div className="notice"><Sparkles size={16} /><div><strong className="text-xs">Gợi ý chăm sóc</strong><p className="mt-1 text-[11px] opacity-80">Khách có thể được nhắc lịch phục hồi da trong 12 ngày tới.</p></div></div></div></div>
    {toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>;
}